# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 Checkout main branch from Github
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - set up JDK 1.8
        uses: actions/setup-java@v1
        with: 
           java-version: 1.8
  

      # Runs a set of commands using the runners shell
      - name: Step 3 - Build Maven Project
        run: mvn -B package --file pom.xml
      
     
      - name: build docker image
        run: docker build . --file Dockerfile --tag image-githubaction:$(date +%s)
          
      - name: push image to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: 46990406
          password: 04june1999
          repository: 46990406/image-githubaction
          tags: latest

            
      - name: deploy to comtainer
        uses: fifsky/ssh-action@master
        with:
        
            
          host: 13.127.45.141
          user: ubuntu
          key: ${{ secrets.PRIVATE_KEY}} 
          
          script: |
                sh "ssh -o StrictHostKeyChecking=no ubuntu@13.127.45.141 docker rm -f shoppingcartcontainer || true"
                sh "ssh -o StrictHostKeyChecking=no ubuntu@13.127.45.141 docker run -d -p 8080:8080 --name shoppingcartcontainer 46990406/image-githubaction:latest"


